package com.example.masterdev_networking.model.modelLogin

data class Details(
    val current_address_detail: String,
    val current_address_district: String,
    val current_address_province: String,
    val current_address_sub_district: String,
    val current_district: String,
    val current_province: String,
    val current_sub_district: String,
    val degree: String,
    val ethnic: String,
    val ethnic_text: String,
    val image_profile: String,
    val marital_status: String,
    val nationality: String,
    val nationality_text: String,
    val native_country_district: String,
    val native_country_province: String,
    val native_country_sub_district: String,
    val native_district: String,
    val native_province: String,
    val native_sub_district: String,
    val personal_email: String,
    val poi_personal_id_number: String,
    val poi_personal_name: String,
    val resident_address_detail: String,
    val resident_address_district: String,
    val resident_address_province: String,
    val resident_address_sub_district: String,
    val resident_district: String,
    val resident_province: String,
    val resident_sub_district: String,
    val staff_code: String,
    val tel: String
)